<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.336">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joshua Harper">
<meta name="dcterms.date" content="2023-04-22">

<title>JH - Pass or Crash: Investigating the Link between Driving Test Pass Rates and Accident Numbers.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">JH</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Joshua Harper</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JoshuaHarper98" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/joshuaharper-" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page">
      <h1 class="title">Pass or Crash: Investigating the Link between Driving Test Pass Rates and Accident Numbers.</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">python</div>
                <div class="quarto-category">visualisation</div>
                <div class="quarto-category">statistics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Joshua Harper </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 22, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block column-page" id="quarto-document-content">




<p>In this data-driven investigation, we will use statistics and Python to explore the potential association between driving test pass rates and the number of road accidents.</p>
<div class="cell" data-execution_count="1">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Statistical Analysis</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(rc<span class="op">=</span>{<span class="st">"figure.figsize"</span>: (<span class="dv">16</span>, <span class="dv">8</span>)})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The data used in this analysis was collected from publicly available resources. The driver test centre data was collected from:</p>
<ul>
<li>Scotland, England, Wales - https://www.gov.uk/government/statistical-data-sets/car-driving-test-data-by-test-centre</li>
<li>Northern Ireland - https://www.opendatani.gov.uk/dataset/driver-testing-outcomes-by-test-centre</li>
</ul>
<p>The accident data was collected from STATS19. Further information on how to access this data can be found here: https://docs.ropensci.org/stats19/index.html</p>
<p>After collecting the data, I used web scrapping to find the postcode of each driving test centre. I then used GeoPy to extract the latitude and longitude from the postcodes. I mapped the coordinates of each accident to the coordinates of the nearest driving centre using the haversine formula:</p>
<p><span class="math display">\[
  haversin\left(\frac{d}{r}\right) = haversin\left(\phi_{1} - \phi_{2}\right) + cos\left(\phi_{1}\right)cos\left(\phi_{2}\right)haversin\left(\lambda_{1} - \lambda_{2}\right),
\]</span></p>
<p>where <span class="math inline">\(r\)</span> is the radius of the earth, <span class="math inline">\(d\)</span> is the distance between two points, <span class="math inline">\(\phi_{1}, \phi_{2}\)</span> are the latitudes of the two points and <span class="math inline">\(\lambda_{1}, \lambda_{2}\)</span> are the longitudes of the two points.</p>
<p>Let’s load the data and see what information we have!</p>
<div class="cell" data-execution_count="2">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(<span class="st">'crashes_merged_2017_to_2020.csv'</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                   engine<span class="op">=</span><span class="st">'pyarrow'</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                   encoding<span class="op">=</span><span class="st">'ISO-8859-1'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="3">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data.head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">accident_index</th>
<th data-quarto-table-cell-role="th">accident_year</th>
<th data-quarto-table-cell-role="th">accident_severity</th>
<th data-quarto-table-cell-role="th">number_of_vehicles</th>
<th data-quarto-table-cell-role="th">number_of_casualties</th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">2020_passrate</th>
<th data-quarto-table-cell-role="th">2019_passrate</th>
<th data-quarto-table-cell-role="th">2018_passrate</th>
<th data-quarto-table-cell-role="th">2017_passrate</th>
<th data-quarto-table-cell-role="th">2020_conducted</th>
<th data-quarto-table-cell-role="th">2019_conducted</th>
<th data-quarto-table-cell-role="th">2018_conducted</th>
<th data-quarto-table-cell-role="th">2017_conducted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Fatal</td>
<td>2</td>
<td>3</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Slight</td>
<td>2</td>
<td>1</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Slight</td>
<td>2</td>
<td>4</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Slight</td>
<td>2</td>
<td>1</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Slight</td>
<td>2</td>
<td>1</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Slight</td>
<td>2</td>
<td>1</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Slight</td>
<td>1</td>
<td>1</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Slight</td>
<td>2</td>
<td>1</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Slight</td>
<td>1</td>
<td>1</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>2.017010e+12</td>
<td>2017</td>
<td>Slight</td>
<td>2</td>
<td>1</td>
<td>Tottenham</td>
<td>43.046875</td>
<td>39.634783</td>
<td>37.53915</td>
<td>37.65838824</td>
<td>1280</td>
<td>5750.0</td>
<td>4470.0</td>
<td>3946</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>For each accident, we have <strong>accident_severity</strong>: the severity of the accident - Slight, Serious or Fatal. The <strong>number_of_vehicles</strong> and <strong>number_of_casualties</strong> in each accident. The year of the accident, <strong>accident_year</strong>. The <strong>nearest_test_centre</strong> to the accident, along with the pass rates for the years <strong>2020_passrate</strong>, <strong>2019_passrate</strong>, <strong>2018_passrate</strong> and <strong>2017_passrate</strong>, along with the respective <strong>20XX_conducted</strong> the number of tests conducted for that year.</p>
<p>We will first check the data for any errors that may have been inherited from Excel.</p>
<div class="cell" data-execution_count="4">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>accident_index          float64
accident_year             int64
accident_severity        object
number_of_vehicles        int64
number_of_casualties      int64
nearest_test_centre      object
2020_passrate            object
2019_passrate           float64
2018_passrate           float64
2017_passrate            object
2020_conducted           object
2019_conducted          float64
2018_conducted          float64
2017_conducted           object
dtype: object</code></pre>
</div>
</div>
<p>Some features we expect to be numeric are being loaded as objects, this is most likely due to loading missing values incorrectly.</p>
<div class="cell" data-execution_count="5">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> data[<span class="op">~</span>(data <span class="op">==</span> <span class="st">''</span>).<span class="bu">any</span>(axis<span class="op">=</span><span class="dv">1</span>)]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> data[<span class="op">~</span>(data <span class="op">==</span> <span class="st">'..'</span>).<span class="bu">any</span>(axis<span class="op">=</span><span class="dv">1</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="6">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'2020_passrate'</span>] <span class="op">=</span> data[<span class="st">'2020_passrate'</span>].astype(<span class="st">'float64'</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'2017_passrate'</span>] <span class="op">=</span> data[<span class="st">'2017_passrate'</span>].astype(<span class="st">'float64'</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'2020_conducted'</span>] <span class="op">=</span> data[<span class="st">'2020_conducted'</span>].astype(<span class="st">'float64'</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'2017_conducted'</span>] <span class="op">=</span> data[<span class="st">'2017_conducted'</span>].astype(<span class="st">'float64'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="7">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data.isna().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>accident_index          52858
accident_year               0
accident_severity           0
number_of_vehicles          0
number_of_casualties        0
nearest_test_centre         0
2020_passrate               0
2019_passrate               0
2018_passrate               0
2017_passrate               0
2020_conducted              0
2019_conducted              0
2018_conducted              0
2017_conducted              0
dtype: int64</code></pre>
</div>
</div>
<p>The data now looks to be correct. Next, we will plot the average driving test pass rate and the average number of accidents over the observed period.</p>
<div class="cell" data-execution_count="8">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(ncols<span class="op">=</span><span class="dv">2</span>, sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>(data.groupby(<span class="st">'nearest_test_centre'</span>).mean()[[</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'2020_passrate'</span>, <span class="st">'2019_passrate'</span>, <span class="st">'2018_passrate'</span>, <span class="st">'2017_passrate'</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>]].rename(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>{</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">'2017_passrate'</span>: <span class="dv">2017</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">'2018_passrate'</span>: <span class="dv">2018</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">'2019_passrate'</span>: <span class="dv">2019</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">'2020_passrate'</span>: <span class="dv">2020</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    }).melt(var_name<span class="op">=</span><span class="st">'Year'</span>, value_name<span class="op">=</span><span class="st">'Pass Rate'</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>            ignore_index<span class="op">=</span><span class="va">False</span>).reset_index(drop<span class="op">=</span><span class="va">False</span>)),</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>             x<span class="op">=</span><span class="st">'Year'</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>             y<span class="op">=</span><span class="st">'Pass Rate'</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>             ax<span class="op">=</span>ax1)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>data.groupby(<span class="st">'accident_year'</span>)[<span class="st">'accident_index'</span>].count(),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>             ax<span class="op">=</span>ax2)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>ax1.title.set_text(<span class="st">'Average driving test pass rate'</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>ax2.title.set_text(<span class="st">'Average number of accidents'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-9-output-1.png" width="1258" height="677"></p>
</div>
</div>
<p>From the first plot, The pass rates of driving tests from 2017 to 2019 remained relatively stable, ranging from 48.88% to 49.33%. However, there was a noticeable increase in the pass rate to 53.23% in 2020. Similarly, the second plot shows a general decreasing trend in accident rates between 2017 and 2019, with a larger decrease in 2020. This spike in pass rates and a significant drop in accident rates could be due to various reasons, such as improved driving habits, improved road safety measures, or even the impact of the COVID-19 pandemic on testing and driving patterns. It is not conclusive at this stage if there is a direct association between the two results.</p>
<p>We will now create a new feature, <strong>passrate</strong>, that combines the four pass rate columns.</p>
<div class="cell" data-execution_count="9">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'passrate'</span>] <span class="op">=</span> (data[[</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'2017_passrate'</span>, <span class="st">'2018_passrate'</span>, <span class="st">'2019_passrate'</span>, <span class="st">'2020_passrate'</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>]].values[np.where(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    data[<span class="st">'accident_year'</span>].values.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="op">==</span> [<span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>, <span class="dv">2020</span>])])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Grouping the data by <strong>nearest_driving_test_centre</strong> and <strong>accident_year</strong>.</p>
<div class="cell" data-execution_count="10">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>grouped_df <span class="op">=</span> (data.assign(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    slight_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Slight'</span>).assign(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        serious_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Serious'</span>).assign(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>            fatal_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Fatal'</span>).groupby([</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">'nearest_test_centre'</span>, <span class="st">'accident_year'</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>            ]).agg(passrate<span class="op">=</span>(<span class="st">'passrate'</span>, np.mean),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                   number_of_accidents<span class="op">=</span>(<span class="st">'nearest_test_centre'</span>, <span class="st">'count'</span>),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>                   number_of_slight_accidents<span class="op">=</span>(<span class="st">'slight_accident'</span>, np.<span class="bu">sum</span>),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>                   number_of_serious_accidents<span class="op">=</span>(<span class="st">'serious_accident'</span>, np.<span class="bu">sum</span>),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>                   number_of_fatal_accidents<span class="op">=</span>(<span class="st">'fatal_accident'</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>                                              np.<span class="bu">sum</span>)).reset_index(drop<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can now plot the distribution of the driving test pass rates, highlighting the year the test took place.</p>
<div class="cell" data-execution_count="11">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>grouped_df, x<span class="op">=</span><span class="st">'passrate'</span>, hue<span class="op">=</span><span class="st">'accident_year'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>&lt;AxesSubplot:xlabel='passrate', ylabel='Count'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-12-output-2.png" width="1258" height="657"></p>
</div>
</div>
<p>The histogram reinforces the conclusions seen earlier, the pass rates for 2017 to 2019 have a roughly similar shape. Whereas the pass rates for 2020 are more right-skewed. The mean pass rate over the 4 years is <strong>50.0976998216524%</strong></p>
<div class="cell" data-execution_count="12">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>grouped_df, x<span class="op">=</span><span class="st">'number_of_accidents'</span>, hue<span class="op">=</span><span class="st">'accident_year'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>&lt;AxesSubplot:xlabel='number_of_accidents', ylabel='Count'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-13-output-2.png" width="1258" height="657"></p>
</div>
</div>
<p>The histogram shows that the number of accidents per year is highly right-skewed for all 4 years. The mean number of accidents per year is <strong>373.5821917808219</strong>. There appear to be many test centres with 0 or close to 0 accidents a year. To investigate this further, we will look at the test centres with extreme values for both the number of accidents and the pass rates.</p>
<p>Looking first at test centres with the lowest number of accidents and the highest pass rates.</p>
<div class="cell" data-execution_count="13">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>grouped_df.sort_values([<span class="st">'number_of_accidents'</span>, <span class="st">'passrate'</span>],</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                       ascending<span class="op">=</span>[<span class="va">True</span>, <span class="va">False</span>]).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">accident_year</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">number_of_accidents</th>
<th data-quarto-table-cell-role="th">number_of_slight_accidents</th>
<th data-quarto-table-cell-role="th">number_of_serious_accidents</th>
<th data-quarto-table-cell-role="th">number_of_fatal_accidents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">219</td>
<td>Buckie</td>
<td>2020</td>
<td>54.545455</td>
<td>4</td>
<td>1</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">247</td>
<td>Campbeltown</td>
<td>2020</td>
<td>76.470588</td>
<td>7</td>
<td>4</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">246</td>
<td>Campbeltown</td>
<td>2019</td>
<td>73.684211</td>
<td>7</td>
<td>4</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">217</td>
<td>Buckie</td>
<td>2018</td>
<td>57.094595</td>
<td>7</td>
<td>2</td>
<td>3</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">703</td>
<td>Lochgilphead</td>
<td>2020</td>
<td>74.074074</td>
<td>8</td>
<td>4</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">479</td>
<td>Golspie</td>
<td>2020</td>
<td>73.333333</td>
<td>8</td>
<td>6</td>
<td>2</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1019</td>
<td>Stranraer</td>
<td>2020</td>
<td>67.500000</td>
<td>8</td>
<td>5</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1015</td>
<td>Stornoway</td>
<td>2020</td>
<td>65.591398</td>
<td>8</td>
<td>5</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">459</td>
<td>Girvan</td>
<td>2020</td>
<td>63.636364</td>
<td>8</td>
<td>4</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">375</td>
<td>Dunoon</td>
<td>2020</td>
<td>62.745098</td>
<td>8</td>
<td>5</td>
<td>2</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Unsurprisingly, the test centres with the lowest number of accidents are in areas that have low population sizes. The pass rates do appear to be significantly higher than the average for the dataset.</p>
<div class="cell" data-execution_count="14">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>grouped_df.sort_values([<span class="st">'passrate'</span>, <span class="st">'number_of_accidents'</span>],</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                       ascending<span class="op">=</span>[<span class="va">False</span>, <span class="va">True</span>]).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">accident_year</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">number_of_accidents</th>
<th data-quarto-table-cell-role="th">number_of_slight_accidents</th>
<th data-quarto-table-cell-role="th">number_of_serious_accidents</th>
<th data-quarto-table-cell-role="th">number_of_fatal_accidents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">443</td>
<td>Fraserburgh</td>
<td>2020</td>
<td>82.456140</td>
<td>11</td>
<td>5</td>
<td>6</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">679</td>
<td>Lerwick</td>
<td>2020</td>
<td>80.303030</td>
<td>11</td>
<td>7</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">379</td>
<td>Duns</td>
<td>2020</td>
<td>80.000000</td>
<td>13</td>
<td>3</td>
<td>8</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">635</td>
<td>Kingussie</td>
<td>2020</td>
<td>78.571429</td>
<td>13</td>
<td>7</td>
<td>4</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">701</td>
<td>Lochgilphead</td>
<td>2018</td>
<td>77.181208</td>
<td>22</td>
<td>15</td>
<td>6</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">476</td>
<td>Golspie</td>
<td>2017</td>
<td>76.712329</td>
<td>10</td>
<td>8</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">247</td>
<td>Campbeltown</td>
<td>2020</td>
<td>76.470588</td>
<td>7</td>
<td>4</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">703</td>
<td>Lochgilphead</td>
<td>2020</td>
<td>74.074074</td>
<td>8</td>
<td>4</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">246</td>
<td>Campbeltown</td>
<td>2019</td>
<td>73.684211</td>
<td>7</td>
<td>4</td>
<td>3</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">479</td>
<td>Golspie</td>
<td>2020</td>
<td>73.333333</td>
<td>8</td>
<td>6</td>
<td>2</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Again, we can see that the high pass rate test centres have a low number of accidents. Now looking at the test centres with the highest number of accidents and the lowest pass rate</p>
<div class="cell" data-execution_count="15">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>grouped_df.sort_values([<span class="st">'number_of_accidents'</span>, <span class="st">'passrate'</span>],</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                       ascending<span class="op">=</span>[<span class="va">False</span>, <span class="va">True</span>]).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">accident_year</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">number_of_accidents</th>
<th data-quarto-table-cell-role="th">number_of_slight_accidents</th>
<th data-quarto-table-cell-role="th">number_of_serious_accidents</th>
<th data-quarto-table-cell-role="th">number_of_fatal_accidents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">572</td>
<td>Hither Green (London)</td>
<td>2017</td>
<td>46.643311</td>
<td>4306</td>
<td>3665</td>
<td>617</td>
<td>24</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1140</td>
<td>Wood Green (London)</td>
<td>2017</td>
<td>38.481506</td>
<td>4297</td>
<td>3647</td>
<td>634</td>
<td>16</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">573</td>
<td>Hither Green (London)</td>
<td>2018</td>
<td>48.732903</td>
<td>4194</td>
<td>3529</td>
<td>648</td>
<td>17</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">574</td>
<td>Hither Green (London)</td>
<td>2019</td>
<td>48.579034</td>
<td>4097</td>
<td>3490</td>
<td>598</td>
<td>9</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1141</td>
<td>Wood Green (London)</td>
<td>2018</td>
<td>39.565325</td>
<td>3802</td>
<td>3164</td>
<td>629</td>
<td>9</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1142</td>
<td>Wood Green (London)</td>
<td>2019</td>
<td>41.515348</td>
<td>3765</td>
<td>3162</td>
<td>586</td>
<td>17</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">575</td>
<td>Hither Green (London)</td>
<td>2020</td>
<td>45.445577</td>
<td>3183</td>
<td>2703</td>
<td>472</td>
<td>8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1143</td>
<td>Wood Green (London)</td>
<td>2020</td>
<td>43.337881</td>
<td>2804</td>
<td>2406</td>
<td>387</td>
<td>11</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">612</td>
<td>Isleworth (Fleming Way)</td>
<td>2017</td>
<td>42.422118</td>
<td>1932</td>
<td>1659</td>
<td>263</td>
<td>10</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">613</td>
<td>Isleworth (Fleming Way)</td>
<td>2018</td>
<td>43.733762</td>
<td>1879</td>
<td>1545</td>
<td>326</td>
<td>8</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>From this, we notice a trend with the test centres. They all appear to be in London, the most densely populated area in the UK. This highlights a fundamental issue of the data, the number of accidents is not normalised by population size.</p>
<div class="cell" data-execution_count="16">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>grouped_df.sort_values([<span class="st">'passrate'</span>, <span class="st">'number_of_accidents'</span>],</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                       ascending<span class="op">=</span>[<span class="va">True</span>, <span class="va">False</span>]).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">accident_year</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">number_of_accidents</th>
<th data-quarto-table-cell-role="th">number_of_slight_accidents</th>
<th data-quarto-table-cell-role="th">number_of_serious_accidents</th>
<th data-quarto-table-cell-role="th">number_of_fatal_accidents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">415</td>
<td>Erith (London)</td>
<td>2020</td>
<td>29.806530</td>
<td>162</td>
<td>136</td>
<td>26</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">412</td>
<td>Erith (London)</td>
<td>2017</td>
<td>30.580880</td>
<td>212</td>
<td>178</td>
<td>33</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">898</td>
<td>Rochdale (Manchester)</td>
<td>2019</td>
<td>30.779165</td>
<td>277</td>
<td>210</td>
<td>61</td>
<td>6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">414</td>
<td>Erith (London)</td>
<td>2019</td>
<td>31.618544</td>
<td>211</td>
<td>175</td>
<td>35</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">130</td>
<td>Birmingham (South Yardley)</td>
<td>2019</td>
<td>31.693198</td>
<td>890</td>
<td>762</td>
<td>127</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">107</td>
<td>Belvedere (London)</td>
<td>2020</td>
<td>32.560386</td>
<td>472</td>
<td>405</td>
<td>66</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">129</td>
<td>Birmingham (South Yardley)</td>
<td>2018</td>
<td>32.768549</td>
<td>884</td>
<td>766</td>
<td>113</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">104</td>
<td>Belvedere (London)</td>
<td>2017</td>
<td>32.875458</td>
<td>599</td>
<td>531</td>
<td>66</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">413</td>
<td>Erith (London)</td>
<td>2018</td>
<td>33.023107</td>
<td>227</td>
<td>185</td>
<td>38</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">105</td>
<td>Belvedere (London)</td>
<td>2018</td>
<td>33.225749</td>
<td>518</td>
<td>442</td>
<td>73</td>
<td>3</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This shows that the lower pass rate test centres do have a higher number of accidents, but again we must highlight the test centres appear to be in highly populated areas.</p>
<p>We will now plot the pass rate against the number of accidents to investigate if there are any obvious trends.</p>
<div class="cell" data-execution_count="17">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>grouped_df,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                x<span class="op">=</span><span class="st">'passrate'</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                y<span class="op">=</span><span class="st">'number_of_accidents'</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                hue<span class="op">=</span><span class="st">'accident_year'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>&lt;AxesSubplot:xlabel='passrate', ylabel='number_of_accidents'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-18-output-2.png" width="1275" height="657"></p>
</div>
</div>
<p>The scatter plot shows evidence of a weak relationship between pass rate and the number of accidents, specifically, we can see that the test centres with low pass rates tend to have a higher number of accidents. We can also see that there appears to be greater volatility in the number of accidents for the lower pass rate test centres. There also appear to be some noticeable outliers, test centres that have a high number of accidents.</p>
<p>To further investigate the relationship, we will calculate the correlation matrix.</p>
<div class="cell" data-execution_count="18">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> np.triu(np.ones_like(grouped_df.corr(method<span class="op">=</span><span class="st">'kendall'</span>), dtype<span class="op">=</span><span class="bu">bool</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>cmap <span class="op">=</span> sns.diverging_palette(<span class="dv">230</span>, <span class="dv">20</span>, as_cmap<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>sns.heatmap(grouped_df.corr(),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>            mask<span class="op">=</span>mask,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>            cmap<span class="op">=</span>cmap,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>            vmax<span class="op">=</span><span class="fl">.3</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>            center<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>            square<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>            linewidths<span class="op">=</span><span class="fl">.5</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>            cbar_kws<span class="op">=</span>{<span class="st">"shrink"</span>: <span class="fl">.5</span>},</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>            annot<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>&lt;AxesSubplot:&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-19-output-2.png" width="935" height="819"></p>
</div>
</div>
<p>This matrix shows that there is evidence of a weak to moderate negative relationship between the pass rate and the number of accidents. This relationship is also consistent over the accident types, with the number of fatal accidents having the lowest correlation with pass rate. Earlier we proposed that the trend of pass rates increasing and accident numbers decreasing in 2020 was due to the driving restrictions in place during the Covid-19 pandemic. Does this hidden effect add uncertainty to these values? We will remove the year 2020 from the dataset and recalculate the correlation matrix.</p>
<div class="cell" data-execution_count="19">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> np.triu(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    np.ones_like(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>        grouped_df[grouped_df[<span class="st">'accident_year'</span>] <span class="op">&lt;</span> <span class="dv">2020</span>].corr(method<span class="op">=</span><span class="st">'kendall'</span>),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>        dtype<span class="op">=</span><span class="bu">bool</span>))</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>cmap <span class="op">=</span> sns.diverging_palette(<span class="dv">230</span>, <span class="dv">20</span>, as_cmap<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>sns.heatmap(grouped_df[grouped_df[<span class="st">'accident_year'</span>] <span class="op">&lt;</span> <span class="dv">2020</span>].corr(),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>            mask<span class="op">=</span>mask,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>            cmap<span class="op">=</span>cmap,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>            vmax<span class="op">=</span><span class="fl">.3</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>            center<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>            square<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>            linewidths<span class="op">=</span><span class="fl">.5</span>,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>            cbar_kws<span class="op">=</span>{<span class="st">"shrink"</span>: <span class="fl">.5</span>},</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>            annot<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>&lt;AxesSubplot:&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-20-output-2.png" width="935" height="819"></p>
</div>
</div>
<p>This matrix shows that the relationship is consistent before the pandemic.</p>
<p>We will now attempt to fit a linear regression model to investigate the relationship further.</p>
<div class="cell" data-execution_count="20">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'passrate'</span>, y<span class="op">=</span><span class="st">'number_of_accidents'</span>, data<span class="op">=</span>grouped_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>&lt;AxesSubplot:xlabel='passrate', ylabel='number_of_accidents'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-21-output-2.png" width="1275" height="657"></p>
</div>
</div>
<div class="cell" data-execution_count="21">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>model_1 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'number_of_accidents ~ passrate + accident_year'</span>,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                  data<span class="op">=</span>grouped_df).fit()</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_1.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                             OLS Regression Results                            
===============================================================================
Dep. Variable:     number_of_accidents   R-squared:                       0.151
Model:                             OLS   Adj. R-squared:                  0.149
Method:                  Least Squares   F-statistic:                     103.4
Date:                 Wed, 17 May 2023   Prob (F-statistic):           4.66e-42
Time:                         21:32:00   Log-Likelihood:                -8568.3
No. Observations:                 1168   AIC:                         1.714e+04
Df Residuals:                     1165   BIC:                         1.716e+04
Df Model:                            2                                         
Covariance Type:             nonrobust                                         
=================================================================================
                    coef    std err          t      P&gt;|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept      3.657e+04   1.99e+04      1.839      0.066   -2439.465    7.56e+04
passrate        -18.3997      1.333    -13.806      0.000     -21.014     -15.785
accident_year   -17.4747      9.855     -1.773      0.076     -36.810       1.861
==============================================================================
Omnibus:                     1334.802   Durbin-Watson:                   0.555
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           120015.268
Skew:                           5.696   Prob(JB):                         0.00
Kurtosis:                      51.335   Cond. No.                     3.69e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.69e+06. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<p>The adjusted R-squared value of 0.149 indicates that the model explains only 14.9% of the variance in the number_of_accidents.</p>
<p>The F-statistic of 103.4 and a p-value of 4.66e-42 indicate that the model as a whole is significant. This means that at least one of the independent variables in the model is significant in explaining the number_of_accidents.</p>
<p>For the individual independent variables, passrate has a t-statistic of -13.806 and a p-value of 0.000, indicating that it is significant in explaining the number_of_accidents. The accident_year variable has a t-statistic of -1.773 and a p-value of 0.076, indicating that it is not significant in explaining the number_of_accidents at the 5% significance level.</p>
<p>The coefficients of the regression indicate that for a 1 percent increase in passrate, the number_of_accidents decreases by 13.806 on average.</p>
<p>The Omnibus test has a p-value of 0.000, indicating that the residuals are not normally distributed. The Skew and Kurtosis values are also large and positive, indicating that the residuals are heavily skewed to the right and have a peaked distribution.</p>
<p>The condition number of 3.69e+06 is large, which indicates the presence of multicollinearity or other numerical problems. This could lead to unstable and unreliable regression coefficients and suggests that caution should be taken when interpreting the results.</p>
<div class="cell" data-execution_count="22">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>pred_ols <span class="op">=</span> model_1.get_prediction()</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>iv_l <span class="op">=</span> pred_ols.summary_frame()[<span class="st">"obs_ci_lower"</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>iv_u <span class="op">=</span> pred_ols.summary_frame()[<span class="st">"obs_ci_upper"</span>]</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_df[<span class="st">'nearest_test_centre'</span>],</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>        grouped_df[<span class="st">'number_of_accidents'</span>],</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"o"</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"data"</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_df[<span class="st">'nearest_test_centre'</span>],</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>        model_1.fittedvalues,</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"r--."</span>,</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"OLS"</span>)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_df[<span class="st">'nearest_test_centre'</span>], iv_u, <span class="st">"r--"</span>)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_df[<span class="st">'nearest_test_centre'</span>], iv_l, <span class="st">"r--"</span>)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"best"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>&lt;matplotlib.legend.Legend at 0x164c94f3af0&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-23-output-2.png" width="1264" height="637"></p>
</div>
</div>
<p>The plot of the observed values versus the fitted values with the confidence interval included shows that, for most test centres, the model fits the number_of_accidents between the confidence interval. There are several outliters, with test_centres have higher accident numbers than fitted. We will use an influence plot to investigate some of the outliers.</p>
<div class="cell" data-execution_count="23">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> sm.graphics.influence_plot(model_1, criterion<span class="op">=</span><span class="st">"cooks"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-24-output-1.png" width="1264" height="692"></p>
</div>
</div>
<div class="cell" data-execution_count="24">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>grouped_df[grouped_df[<span class="st">'nearest_test_centre'</span>] <span class="op">==</span> grouped_df.iloc[<span class="dv">572</span>]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>           [<span class="st">'nearest_test_centre'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="24">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">accident_year</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">number_of_accidents</th>
<th data-quarto-table-cell-role="th">number_of_slight_accidents</th>
<th data-quarto-table-cell-role="th">number_of_serious_accidents</th>
<th data-quarto-table-cell-role="th">number_of_fatal_accidents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">572</td>
<td>Hither Green (London)</td>
<td>2017</td>
<td>46.643311</td>
<td>4306</td>
<td>3665</td>
<td>617</td>
<td>24</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">573</td>
<td>Hither Green (London)</td>
<td>2018</td>
<td>48.732903</td>
<td>4194</td>
<td>3529</td>
<td>648</td>
<td>17</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">574</td>
<td>Hither Green (London)</td>
<td>2019</td>
<td>48.579034</td>
<td>4097</td>
<td>3490</td>
<td>598</td>
<td>9</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">575</td>
<td>Hither Green (London)</td>
<td>2020</td>
<td>45.445577</td>
<td>3183</td>
<td>2703</td>
<td>472</td>
<td>8</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The Hither Green test centre accounts for outliers 572, 573, 574, and 575. We can see that the test centre has a below average pass rate and an extremely high number of accidents.</p>
<div class="cell" data-execution_count="25">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>grouped_df[grouped_df[<span class="st">'nearest_test_centre'</span>] <span class="op">==</span> grouped_df.iloc[<span class="dv">443</span>]</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>           [<span class="st">'nearest_test_centre'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="25">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">accident_year</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">number_of_accidents</th>
<th data-quarto-table-cell-role="th">number_of_slight_accidents</th>
<th data-quarto-table-cell-role="th">number_of_serious_accidents</th>
<th data-quarto-table-cell-role="th">number_of_fatal_accidents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">440</td>
<td>Fraserburgh</td>
<td>2017</td>
<td>63.576159</td>
<td>20</td>
<td>14</td>
<td>6</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">441</td>
<td>Fraserburgh</td>
<td>2018</td>
<td>60.251046</td>
<td>21</td>
<td>14</td>
<td>6</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">442</td>
<td>Fraserburgh</td>
<td>2019</td>
<td>66.115702</td>
<td>19</td>
<td>11</td>
<td>7</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">443</td>
<td>Fraserburgh</td>
<td>2020</td>
<td>82.456140</td>
<td>11</td>
<td>5</td>
<td>6</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Outlier 443 is the Fraserburgh test centre in 2020. We can see in that year there was a massive improvement in pass rate and just over half the number of accidents compared to previous years.</p>
<p>As accident_year was noted to be statistically insignificant, we will run the analysis again without the accident_year feature. We will first create a new dataset, grouping by only nearest_driving_test_centre. This means for each driving test centre, we will have the total number of accidents over the four years.</p>
<div class="cell" data-execution_count="26">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>grouped_df <span class="op">=</span> (data.assign(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    slight_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Slight'</span>).assign(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>        serious_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Serious'</span>).assign(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>            fatal_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Fatal'</span>).groupby([</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">'nearest_test_centre'</span>, <span class="st">'accident_year'</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>            ]).agg(passrate<span class="op">=</span>(<span class="st">'passrate'</span>, np.mean),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>                   number_of_accidents<span class="op">=</span>(<span class="st">'nearest_test_centre'</span>, <span class="st">'count'</span>),</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>                   number_of_slight_accidents<span class="op">=</span>(<span class="st">'slight_accident'</span>, np.<span class="bu">sum</span>),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>                   number_of_serious_accidents<span class="op">=</span>(<span class="st">'serious_accident'</span>, np.<span class="bu">sum</span>),</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>                   number_of_fatal_accidents<span class="op">=</span>(<span class="st">'fatal_accident'</span>,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>                                              np.<span class="bu">sum</span>)).reset_index(drop<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="27">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>grouped_2_df <span class="op">=</span> (grouped_df.groupby([</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'nearest_test_centre'</span>,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>]).agg(passrate<span class="op">=</span>(<span class="st">'passrate'</span>, np.mean),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>       number_of_accidents<span class="op">=</span>(<span class="st">'number_of_accidents'</span>, np.mean),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>       number_of_slight_accidents<span class="op">=</span>(<span class="st">'number_of_slight_accidents'</span>, np.mean),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>       number_of_serious_accidents<span class="op">=</span>(<span class="st">'number_of_serious_accidents'</span>, np.mean),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>       number_of_fatal_accidents<span class="op">=</span>(<span class="st">'number_of_fatal_accidents'</span>,</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>                                  np.mean)).reset_index(drop<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="28">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>grouped_2_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">number_of_accidents</th>
<th data-quarto-table-cell-role="th">number_of_slight_accidents</th>
<th data-quarto-table-cell-role="th">number_of_serious_accidents</th>
<th data-quarto-table-cell-role="th">number_of_fatal_accidents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Aberdeen North</td>
<td>54.854631</td>
<td>105.75</td>
<td>70.00</td>
<td>34.25</td>
<td>1.50</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Aberdeen South (Cove)</td>
<td>57.237618</td>
<td>57.25</td>
<td>35.25</td>
<td>20.25</td>
<td>1.75</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Abergavenny</td>
<td>58.753888</td>
<td>110.50</td>
<td>74.25</td>
<td>32.00</td>
<td>4.25</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Aberystwyth (Park Avenue)</td>
<td>53.623044</td>
<td>120.00</td>
<td>91.75</td>
<td>25.75</td>
<td>2.50</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Airdrie</td>
<td>47.398923</td>
<td>192.50</td>
<td>148.75</td>
<td>40.75</td>
<td>3.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">287</td>
<td>Workington</td>
<td>53.100607</td>
<td>284.75</td>
<td>221.75</td>
<td>58.25</td>
<td>4.75</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">288</td>
<td>Worksop</td>
<td>55.829321</td>
<td>297.75</td>
<td>216.75</td>
<td>73.50</td>
<td>7.50</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">289</td>
<td>Wrexham</td>
<td>42.650556</td>
<td>218.25</td>
<td>161.50</td>
<td>53.50</td>
<td>3.25</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">290</td>
<td>Yeovil</td>
<td>62.411467</td>
<td>348.00</td>
<td>289.00</td>
<td>53.25</td>
<td>5.75</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">291</td>
<td>York</td>
<td>52.422700</td>
<td>441.75</td>
<td>371.00</td>
<td>63.75</td>
<td>7.00</td>
</tr>
</tbody>
</table>

<p>292 rows × 6 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="29">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>model_2 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'number_of_accidents ~ passrate'</span>,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                  data<span class="op">=</span>grouped_2_df).fit()</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_2.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                             OLS Regression Results                            
===============================================================================
Dep. Variable:     number_of_accidents   R-squared:                       0.158
Model:                             OLS   Adj. R-squared:                  0.155
Method:                  Least Squares   F-statistic:                     54.24
Date:                 Wed, 17 May 2023   Prob (F-statistic):           1.85e-12
Time:                         21:32:11   Log-Likelihood:                -2136.4
No. Observations:                  292   AIC:                             4277.
Df Residuals:                      290   BIC:                             4284.
Df Model:                            1                                         
Covariance Type:             nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1399.5167    140.937      9.930      0.000    1122.128    1676.905
passrate     -20.4787      2.781     -7.365      0.000     -25.952     -15.006
==============================================================================
Omnibus:                      366.583   Durbin-Watson:                   2.150
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            27816.188
Skew:                           5.653   Prob(JB):                         0.00
Kurtosis:                      49.459   Cond. No.                         334.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>This model appears to be a slight improvement to the previous model:</p>
<ul>
<li>The adjusted R-squared has improved from 0.149 to 0.155, indicating that the model may be a better fit.</li>
<li>The coefficient of passrate has decreased from -18.3997 to -20.4787, this suggests a stronger negative association between passrate and the number of accidents.</li>
<li>The issues of non-normality of the residuals persists for this model.</li>
</ul>
<div class="cell" data-execution_count="30">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>pred_ols <span class="op">=</span> model_2.get_prediction()</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>iv_l <span class="op">=</span> pred_ols.summary_frame()[<span class="st">"obs_ci_lower"</span>]</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>iv_u <span class="op">=</span> pred_ols.summary_frame()[<span class="st">"obs_ci_upper"</span>]</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_2_df[<span class="st">'nearest_test_centre'</span>],</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>        grouped_2_df[<span class="st">'number_of_accidents'</span>],</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"o"</span>,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"data"</span>)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_2_df[<span class="st">'nearest_test_centre'</span>],</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>        model_2.fittedvalues,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"r--."</span>,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"OLS"</span>)</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_2_df[<span class="st">'nearest_test_centre'</span>], iv_u, <span class="st">"r--"</span>)</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_2_df[<span class="st">'nearest_test_centre'</span>], iv_l, <span class="st">"r--"</span>)</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"best"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>&lt;matplotlib.legend.Legend at 0x164ca992f50&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-31-output-2.png" width="1264" height="637"></p>
</div>
</div>
<p>The plot of the observed values versus the fitted values shows a similar number of outliers compared to the plot for model 1. We should note that model 2 was fit on 292 observations compared to 1168 for model 1. Therefore, we should expect a similar decrease in the number of outliers. We will now use an influence plot to investigate these outliers.</p>
<div class="cell" data-execution_count="31">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> sm.graphics.influence_plot(model_2, criterion<span class="op">=</span><span class="st">"cooks"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-32-output-1.png" width="1264" height="688"></p>
</div>
</div>
<div class="cell" data-execution_count="32">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>grouped_2_df[grouped_2_df[<span class="st">'nearest_test_centre'</span>] <span class="op">==</span> grouped_2_df.iloc[<span class="dv">143</span>]</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>             [<span class="st">'nearest_test_centre'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="32">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">number_of_accidents</th>
<th data-quarto-table-cell-role="th">number_of_slight_accidents</th>
<th data-quarto-table-cell-role="th">number_of_serious_accidents</th>
<th data-quarto-table-cell-role="th">number_of_fatal_accidents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">143</td>
<td>Hither Green (London)</td>
<td>47.350206</td>
<td>3945.0</td>
<td>3346.75</td>
<td>583.75</td>
<td>14.5</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="33">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>grouped_2_df[grouped_2_df[<span class="st">'nearest_test_centre'</span>] <span class="op">==</span> grouped_2_df.iloc[<span class="dv">94</span>]</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>             [<span class="st">'nearest_test_centre'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="33">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">number_of_accidents</th>
<th data-quarto-table-cell-role="th">number_of_slight_accidents</th>
<th data-quarto-table-cell-role="th">number_of_serious_accidents</th>
<th data-quarto-table-cell-role="th">number_of_fatal_accidents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">94</td>
<td>Duns</td>
<td>72.56084</td>
<td>16.75</td>
<td>9.75</td>
<td>6.0</td>
<td>1.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The Hither Green test centre is once again an outlier with a lower than average pass rate and a very high number of accidents. Outlier 94 is the Duns test centre with an extremely high pass rate and low number of accidents.</p>
<p>We noted earlier that the true effect of pass rate on accident rates may be uncertain due to the number of accidents not accouting for differences in population size. Therefore, higher-population areas have a higher number of crashes. To attempt to mitigate this issue, we will use the number of driving tests conducted as a pseudo value for population size.</p>
<div class="cell" data-execution_count="34">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'conducted'</span>] <span class="op">=</span> (data[[</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'2017_conducted'</span>, <span class="st">'2018_conducted'</span>, <span class="st">'2019_conducted'</span>, <span class="st">'2020_conducted'</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>]].values[np.where(</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    data[<span class="st">'accident_year'</span>].values.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="op">==</span> [<span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>, <span class="dv">2020</span>])])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="35">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>grouped_df <span class="op">=</span> (data.assign(</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>    slight_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Slight'</span>).assign(</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>        serious_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Serious'</span>).assign(</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>            fatal_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Fatal'</span>).groupby([</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">'nearest_test_centre'</span>, <span class="st">'accident_year'</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>            ]).agg(passrate<span class="op">=</span>(<span class="st">'passrate'</span>, np.mean),</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>                   conducted<span class="op">=</span>(<span class="st">'conducted'</span>, np.mean),</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>                   number_of_accidents<span class="op">=</span>(<span class="st">'nearest_test_centre'</span>, <span class="st">'count'</span>),</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>                   number_of_slight_accidents<span class="op">=</span>(<span class="st">'slight_accident'</span>, np.<span class="bu">sum</span>),</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>                   number_of_serious_accidents<span class="op">=</span>(<span class="st">'serious_accident'</span>, np.<span class="bu">sum</span>),</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>                   number_of_fatal_accidents<span class="op">=</span>(<span class="st">'fatal_accident'</span>,</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>                                              np.<span class="bu">sum</span>)).reset_index(drop<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We divide the number of accidents by the number of tests conducted and multiply by 1000 to get the number of accidents per 1000 tests (or people).</p>
<div class="cell" data-execution_count="36">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>grouped_df[<span class="st">'accidents_adjusted'</span>] <span class="op">=</span> grouped_df[</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'number_of_accidents'</span>] <span class="op">/</span> grouped_df[<span class="st">'conducted'</span>] <span class="op">*</span> <span class="dv">1000</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>grouped_df[<span class="st">'slight_adjusted'</span>] <span class="op">=</span> grouped_df[</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'number_of_slight_accidents'</span>] <span class="op">/</span> grouped_df[<span class="st">'conducted'</span>] <span class="op">*</span> <span class="dv">1000</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>grouped_df[<span class="st">'serious_adjusted'</span>] <span class="op">=</span> grouped_df[</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'number_of_serious_accidents'</span>] <span class="op">/</span> grouped_df[<span class="st">'conducted'</span>] <span class="op">*</span> <span class="dv">1000</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>grouped_df[<span class="st">'fatal_adjusted'</span>] <span class="op">=</span> grouped_df[</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'number_of_fatal_accidents'</span>] <span class="op">/</span> grouped_df[<span class="st">'conducted'</span>] <span class="op">*</span> <span class="dv">1000</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>grouped_df <span class="op">=</span> grouped_df[[</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'nearest_test_centre'</span>, <span class="st">'passrate'</span>, <span class="st">'accidents_adjusted'</span>, <span class="st">'slight_adjusted'</span>,</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'serious_adjusted'</span>, <span class="st">'fatal_adjusted'</span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="37">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>grouped_2_df <span class="op">=</span> (grouped_df.groupby([</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'nearest_test_centre'</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>]).agg(passrate<span class="op">=</span>(<span class="st">'passrate'</span>, np.mean),</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>       accidents_adjusted<span class="op">=</span>(<span class="st">'accidents_adjusted'</span>, np.mean),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>       slight_adjusted<span class="op">=</span>(<span class="st">'slight_adjusted'</span>, np.mean),</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>       serious_adjusted<span class="op">=</span>(<span class="st">'serious_adjusted'</span>, np.mean),</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>       fatal_adjusted<span class="op">=</span>(<span class="st">'fatal_adjusted'</span>, np.mean)).reset_index(drop<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="38">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>grouped_2_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="38">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">accidents_adjusted</th>
<th data-quarto-table-cell-role="th">slight_adjusted</th>
<th data-quarto-table-cell-role="th">serious_adjusted</th>
<th data-quarto-table-cell-role="th">fatal_adjusted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Aberdeen North</td>
<td>54.854631</td>
<td>39.120405</td>
<td>23.829155</td>
<td>14.723623</td>
<td>0.567628</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Aberdeen South (Cove)</td>
<td>57.237618</td>
<td>20.764980</td>
<td>12.104572</td>
<td>7.899692</td>
<td>0.760715</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Abergavenny</td>
<td>58.753888</td>
<td>36.992872</td>
<td>24.321708</td>
<td>11.431776</td>
<td>1.239388</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Aberystwyth (Park Avenue)</td>
<td>53.623044</td>
<td>169.516180</td>
<td>130.009211</td>
<td>36.264133</td>
<td>3.242836</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Airdrie</td>
<td>47.398923</td>
<td>74.426218</td>
<td>53.775133</td>
<td>18.387963</td>
<td>2.263122</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">287</td>
<td>Workington</td>
<td>53.100607</td>
<td>167.157629</td>
<td>126.844385</td>
<td>37.030612</td>
<td>3.282632</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">288</td>
<td>Worksop</td>
<td>55.829321</td>
<td>106.139175</td>
<td>74.833260</td>
<td>28.565052</td>
<td>2.740863</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">289</td>
<td>Wrexham</td>
<td>42.650556</td>
<td>77.457255</td>
<td>56.728892</td>
<td>19.529580</td>
<td>1.198783</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">290</td>
<td>Yeovil</td>
<td>62.411467</td>
<td>98.353587</td>
<td>81.594604</td>
<td>14.977450</td>
<td>1.781533</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">291</td>
<td>York</td>
<td>52.422700</td>
<td>94.550250</td>
<td>78.899257</td>
<td>13.950239</td>
<td>1.700754</td>
</tr>
</tbody>
</table>

<p>292 rows × 6 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="39">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'passrate'</span>, y<span class="op">=</span><span class="st">'accidents_adjusted'</span>, data<span class="op">=</span>grouped_2_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="39">
<pre><code>&lt;AxesSubplot:xlabel='passrate', ylabel='accidents_adjusted'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-40-output-2.png" width="1275" height="657"></p>
</div>
</div>
<p>The scatterplot of pass rate and adjusted accident rates now shows evidence of a positive linear association. Note that there appears to be a fairly large outlier at around ~61% pass rate and ~1190 adjusted accidents.</p>
<div class="cell" data-execution_count="40">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> np.triu(np.ones_like(grouped_2_df.corr(method<span class="op">=</span><span class="st">'kendall'</span>), dtype<span class="op">=</span><span class="bu">bool</span>))</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>cmap <span class="op">=</span> sns.diverging_palette(<span class="dv">230</span>, <span class="dv">20</span>, as_cmap<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>sns.heatmap(grouped_df.corr(method<span class="op">=</span><span class="st">'kendall'</span>),</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>            mask<span class="op">=</span>mask,</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>            cmap<span class="op">=</span>cmap,</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>            vmax<span class="op">=</span><span class="fl">.3</span>,</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>            center<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>            square<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>            linewidths<span class="op">=</span><span class="fl">.5</span>,</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>            cbar_kws<span class="op">=</span>{<span class="st">"shrink"</span>: <span class="fl">.5</span>},</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>            annot<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>&lt;AxesSubplot:&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-41-output-2.png" width="753" height="637"></p>
</div>
</div>
<p>The correlation matrix also shows a positive association between pass rate and the adjusted accident rates. The strongest association is between pass rate and fatal accidents.</p>
<div class="cell" data-execution_count="41">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>model_3 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'accidents_adjusted ~ passrate'</span>,</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>                  data<span class="op">=</span>grouped_2_df).fit()</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_3.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:     accidents_adjusted   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                  0.009
Method:                 Least Squares   F-statistic:                     3.751
Date:                Wed, 17 May 2023   Prob (F-statistic):             0.0537
Time:                        21:32:22   Log-Likelihood:                -1760.9
No. Observations:                 292   AIC:                             3526.
Df Residuals:                     290   BIC:                             3533.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     48.0936     38.948      1.235      0.218     -28.563     124.750
passrate       1.4883      0.768      1.937      0.054      -0.024       3.001
==============================================================================
Omnibus:                      345.971   Durbin-Watson:                   2.023
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21976.918
Skew:                           5.171   Prob(JB):                         0.00
Kurtosis:                      44.223   Cond. No.                         334.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Summary of the model:</p>
<ul>
<li>The adjusted R-squared of 0.013 is significantly lower than the previous two models, indicating that this model is a worse fit to the data.</li>
<li>The coefficient of passrate id positive, indicating a positive association between the pass rate and adjusted accident rates. This is the opposite of the relationship shown in the first model.</li>
<li>The p-value for passrate is not significant at a significance level of 0.05, unlike the previous two models.</li>
<li>The high skewness and kurtosis values also suggest a non-normal distribution of residuals. This could indicate that there might be other variables or non-linear relationships not captured by the model. This is consistent with the previous two models.</li>
</ul>
<div class="cell" data-execution_count="42">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>pred_ols <span class="op">=</span> model_3.get_prediction()</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>iv_l <span class="op">=</span> pred_ols.summary_frame()[<span class="st">"obs_ci_lower"</span>]</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>iv_u <span class="op">=</span> pred_ols.summary_frame()[<span class="st">"obs_ci_upper"</span>]</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_2_df[<span class="st">'nearest_test_centre'</span>],</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>        grouped_2_df[<span class="st">'accidents_adjusted'</span>],</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"o"</span>,</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"data"</span>)</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_2_df[<span class="st">'nearest_test_centre'</span>],</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>        model_3.fittedvalues,</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"r--."</span>,</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"OLS"</span>)</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_2_df[<span class="st">'nearest_test_centre'</span>], iv_u, <span class="st">"r--"</span>)</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>ax.plot(grouped_2_df[<span class="st">'nearest_test_centre'</span>], iv_l, <span class="st">"r--"</span>)</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"best"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="42">
<pre><code>&lt;matplotlib.legend.Legend at 0x164c597da50&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-43-output-2.png" width="1255" height="637"></p>
</div>
</div>
<div class="cell" data-execution_count="43">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> sm.graphics.influence_plot(model_3, criterion<span class="op">=</span><span class="st">"cooks"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-44-output-1.png" width="1264" height="698"></p>
</div>
</div>
<div class="cell" data-execution_count="44">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>grouped_2_df[grouped_2_df[<span class="st">'nearest_test_centre'</span>] <span class="op">==</span> grouped_2_df.iloc[<span class="dv">275</span>]</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>             [<span class="st">'nearest_test_centre'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="44">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nearest_test_centre</th>
<th data-quarto-table-cell-role="th">passrate</th>
<th data-quarto-table-cell-role="th">accidents_adjusted</th>
<th data-quarto-table-cell-role="th">slight_adjusted</th>
<th data-quarto-table-cell-role="th">serious_adjusted</th>
<th data-quarto-table-cell-role="th">fatal_adjusted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">275</td>
<td>Wellingborough</td>
<td>61.390541</td>
<td>1165.93911</td>
<td>855.6676</td>
<td>275.021914</td>
<td>35.249596</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The influence plot below highlights that the most influential outlier is the Wellingborough test centre. This test centre has an above average pass rate but extremely high number of accidents.</p>
<p>After normalising for population size, there no longer appears to be any evidence of an association between driving test pass rates and accident rates. We can show that the main driver of the effect shown in the first model was actually most likely the effect of differences in population size rather than the pass rate of the test centre.</p>
<div class="cell" data-execution_count="45">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>grouped_df <span class="op">=</span> (data.assign(</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>    slight_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Slight'</span>).assign(</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>        serious_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Serious'</span>).assign(</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>            fatal_accident<span class="op">=</span>data[<span class="st">'accident_severity'</span>] <span class="op">==</span> <span class="st">'Fatal'</span>).groupby([</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">'nearest_test_centre'</span>, <span class="st">'accident_year'</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>            ]).agg(passrate<span class="op">=</span>(<span class="st">'passrate'</span>, np.mean),</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>                   conducted<span class="op">=</span>(<span class="st">'conducted'</span>, np.mean),</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>                   number_of_accidents<span class="op">=</span>(<span class="st">'nearest_test_centre'</span>, <span class="st">'count'</span>),</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>                   number_of_slight_accidents<span class="op">=</span>(<span class="st">'slight_accident'</span>, np.<span class="bu">sum</span>),</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>                   number_of_serious_accidents<span class="op">=</span>(<span class="st">'serious_accident'</span>, np.<span class="bu">sum</span>),</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>                   number_of_fatal_accidents<span class="op">=</span>(<span class="st">'fatal_accident'</span>,</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>                                              np.<span class="bu">sum</span>)).reset_index(drop<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>grouped_df,</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>                x<span class="op">=</span><span class="st">'conducted'</span>,</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>                y<span class="op">=</span><span class="st">'passrate'</span>,</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>                hue<span class="op">=</span><span class="st">'accident_year'</span>,</span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>                ax<span class="op">=</span>ax1)</span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>grouped_df,</span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>                x<span class="op">=</span><span class="st">'conducted'</span>,</span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>                y<span class="op">=</span><span class="st">'number_of_accidents'</span>,</span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>                hue<span class="op">=</span><span class="st">'accident_year'</span>,</span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>                ax<span class="op">=</span>ax2)</span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-46-output-1.png" width="1273" height="657"></p>
</div>
</div>
<p>The first plot shows that as the number of test conducted increases; the pass rate decreases. The second plot shows that as the number of tests conducted increases; the number of accidents increases. This shows the source of the negative association between pass rate and the number of accidents.</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>